import {
  SRectangle,
  SRoundedRect,
  SDiamond,
  SDocNotch,
  SParallelogramLeft,
  SEllipse,
  SCapsule,
  SCircle,
  SDatabase,
  SParallelogramRight,
  SCylinder,
  SDocFold,
  SMultiDoc,
  SPredefined,
  SLoop,
  STape,
  SPunchedCard,
  SManualOp,
  STrapBottom,
  STrapTop,
  SHexagon,
  SAnnotation,
  SSemiClosed,
  SOr,
  SMerge,
  SDisplay,
  SBracket,
  STerminator,
  SFlowCard,
  SEqual,
  SSemicircle,
  STrapezoid,
  SIrregular,
  SPentagon,
  SLaneHorizontal,
  SLaneVertical,
  BSquare,
  BRoundedSquare,
  BSoftSquare,
  BCircle,
  BTriangle,
  BDiamond,
  BParallelogram,
  BStar,
  BHalfCircle,
  BTagCapsule,
  BHouse,
  BTrapezoid,
  BHexagon,
  BPlus,
  ALeftBrace,
  ARightBracket,
  ALeftBracket,
  ARightBrace,
  AEqualSign,
  AThreeHoriz,
  AThreeWavy,
  AEquals,
  DRightArrow,
  DLeftArrow,
  DDoubleArrow,
  DCurvedArrow,
  DLeftChevron,
  DRightChevron,
  DRightThick,
  DLeftThick,
  PHexagon,
  LHorizontal,
  LVertical,
} from './shapes'

/* =========================================================
   图形数据定义（模块级常量，避免每次渲染重建）
   ========================================================= */
export const categories = [
  {
    key: 'flowchart',
    label: '流程图',
    subGroups: [
      {
        key: 'flowchart-main',
        label: '流程图',
        items: [
          { key: 'rect', name: '矩形', Comp: SRectangle },
          { key: 'round-rect', name: '圆角矩形', Comp: SRoundedRect },
          { key: 'diamond', name: '菱形', Comp: SDiamond },
          { key: 'doc-notch', name: '文档（缺角）', Comp: SDocNotch },
          { key: 'para-left', name: '平行四边形（左）', Comp: SParallelogramLeft },
          { key: 'ellipse', name: '椭圆', Comp: SEllipse },
          { key: 'capsule', name: '胶囊', Comp: SCapsule },
          { key: 'circle', name: '圆', Comp: SCircle },
          { key: 'database', name: '数据库', Comp: SDatabase },
          { key: 'para-right', name: '平行四边形（右）', Comp: SParallelogramRight },
          { key: 'cylinder', name: '圆柱', Comp: SCylinder },
          { key: 'doc-fold', name: '文档（折角）', Comp: SDocFold },
          { key: 'multi-doc', name: '多文档', Comp: SMultiDoc },
          { key: 'predefined', name: '预定义过程', Comp: SPredefined },
          { key: 'loop', name: '循环', Comp: SLoop },
          { key: 'tape', name: '磁带', Comp: STape },
          { key: 'punched-card', name: '穿孔卡', Comp: SPunchedCard },
          { key: 'manual-op', name: '手动操作', Comp: SManualOp },
          { key: 'trap-bottom', name: '排序（下窄梯形）', Comp: STrapBottom },
          { key: 'trap-top', name: '上窄梯形', Comp: STrapTop },
          { key: 'hexagon', name: '准备/六边形', Comp: SHexagon },
          { key: 'annotation', name: '注释', Comp: SAnnotation },
          { key: 'semi-closed', name: '终止（半闭合）', Comp: SSemiClosed },
          { key: 'or', name: '决策OR', Comp: SOr },
          { key: 'merge', name: '合并', Comp: SMerge },
          { key: 'display', name: '显示', Comp: SDisplay },
          { key: 'bracket', name: '限制符', Comp: SBracket },
          { key: 'terminator', name: '终止符', Comp: STerminator },
          { key: 'flow-card', name: '流程卡片', Comp: SFlowCard },
          { key: 'equal', name: '决策等号', Comp: SEqual },
          { key: 'semicircle', name: '半圆', Comp: SSemicircle },
          { key: 'trapezoid', name: '梯形', Comp: STrapezoid },
          { key: 'irregular', name: '不规则', Comp: SIrregular },
          { key: 'pentagon', name: '五边形', Comp: SPentagon },
        ],
      },
      {
        key: 'swimlane',
        label: '泳道',
        items: [
          { key: 'lane-h', name: '水平泳道', Comp: SLaneHorizontal },
          { key: 'lane-v', name: '垂直泳道', Comp: SLaneVertical },
        ],
      },
    ],
  },
  {
    key: 'basic',
    label: '基础图形',
    subGroups: [
      {
        key: 'basic-main',
        label: '基础图形',
        items: [
          { key: 'b-square', name: '正方形', Comp: BSquare },
          { key: 'b-r-square', name: '圆角正方形', Comp: BRoundedSquare },
          { key: 'b-soft-sq', name: '超圆角正方形', Comp: BSoftSquare },
          { key: 'b-circle', name: '圆形', Comp: BCircle },
          { key: 'b-triangle', name: '三角形', Comp: BTriangle },
          { key: 'b-diamond', name: '菱形', Comp: BDiamond },
          { key: 'b-para', name: '平行四边形', Comp: BParallelogram },
          { key: 'b-star', name: '星形', Comp: BStar },
          { key: 'b-half', name: '半圆', Comp: BHalfCircle },
          { key: 'b-tag', name: '胶囊', Comp: BTagCapsule },
          { key: 'b-house', name: '房子（五边形）', Comp: BHouse },
          { key: 'b-trap', name: '梯形', Comp: BTrapezoid },
          { key: 'b-hex', name: '六边形', Comp: BHexagon },
          { key: 'b-plus', name: '加号', Comp: BPlus },
        ],
      },
      {
        key: 'annotation',
        label: '注释',
        items: [
          { key: 'a-lbrace', name: '左花括号', Comp: ALeftBrace },
          { key: 'a-rbracket', name: '右方括号', Comp: ARightBracket },
          { key: 'a-lbracket', name: '左方括号', Comp: ALeftBracket },
          { key: 'a-rbrace', name: '右花括号', Comp: ARightBrace },
          { key: 'a-equal-sign', name: '等号（特殊）', Comp: AEqualSign },
          { key: 'a-three-horiz', name: '三条横线', Comp: AThreeHoriz },
          { key: 'a-three-wavy', name: '三条波浪', Comp: AThreeWavy },
          { key: 'a-equals', name: '等号（弯）', Comp: AEquals },
        ],
      },
      {
        key: 'direction',
        label: '方向',
        items: [
          { key: 'd-right', name: '向右箭头', Comp: DRightArrow },
          { key: 'd-left', name: '向左箭头', Comp: DLeftArrow },
          { key: 'd-double', name: '双向箭头', Comp: DDoubleArrow },
          { key: 'd-curved', name: '弯曲箭头', Comp: DCurvedArrow },
          { key: 'd-left-ch', name: '左尖括号', Comp: DLeftChevron },
          { key: 'd-right-ch', name: '右尖括号', Comp: DRightChevron },
          { key: 'd-right-tk', name: '粗箭头右', Comp: DRightThick },
          { key: 'd-left-tk', name: '粗箭头左', Comp: DLeftThick },
        ],
      },
      {
        key: 'polygon',
        label: '多边形',
        items: [{ key: 'p-hex', name: '六边形', Comp: PHexagon }],
      },
      {
        key: 'line',
        label: '直线',
        items: [
          { key: 'l-h', name: '横线', Comp: LHorizontal },
          { key: 'l-v', name: '竖线', Comp: LVertical },
        ],
      },
    ],
  },
]
